// Generated by CoffeeScript 1.7.1
(function() {
  var LocalStrategy, app, auth, bodyParser, cookieParser, db, express, favicon, flash, flowers, logger, passport, path, routes, session, user, users;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  flash = require('connect-flash');

  routes = require('./src/routes/index');

  users = require('./src/routes/users');

  flowers = require('./src/routes/flowers');

  auth = require('./src/routes/auth');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  session = require('express-session');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(require('less-middleware')(path.join(__dirname, 'public')));

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use(express["static"](path.join(__dirname, 'dist')));

  app.use(session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: false
  }));

  app.use(flash());

  app.use(passport.initialize());

  app.use(passport.session());

  app.use('/', routes);

  app.use('/users', users);

  app.use('/flowers', flowers);

  app.use('/login', auth);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  user = require("./src/model/user");

  db = require('./db');

  passport.use(new LocalStrategy(user.passport));

  passport.serializeUser(function(user, done) {
    return done(null, user);
  });

  passport.deserializeUser(function(user, done) {
    return done(null, user);
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.map
