// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    res.send('respond with a users');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.map
